parameters:
#    koldunas_main.example.class: Koldunas\MainBundle\Example

services:
#    koldunas_main.example:
#        class: %koldunas_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
